# Generated by Django 3.2.25 on 2024-08-31 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=200)),
                ('fabricante', models.CharField(max_length=200)),
                ('modelo', models.CharField(max_length=200)),
                ('numero_serie', models.CharField(max_length=200)),
                ('data_compra', models.DateField(blank=True, default=None, null=True)),
                ('valor_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
